// Auth
const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
const AUTHENTICATION_SIGNOUT = 'AUTHENTICATION_SIGNOUT';

// User
const USER_FAILURE = 'USER_FAILURE';
const USER_RECIEVE_SINGLUAR = 'USER_RECIEVE_SINGLUAR';

// Series
const SERIES_FAILURE = 'SERIES_FAILURE';
const SERIES_RECIEVE_SINGULAR = 'SERIES_RECIEVE_SINGULAR';
const SERIES_RECIEVE_MULTIPLE = 'SERIES_RECIEVE_MULTIPLE';

export {
    AUTHENTICATION_FAILURE,
    AUTHENTICATION_SUCCESS,
    AUTHENTICATION_SIGNOUT,
    USER_FAILURE,
    USER_RECIEVE_SINGLUAR,
    SERIES_FAILURE,
    SERIES_RECIEVE_SINGULAR,
    SERIES_RECIEVE_MULTIPLE
};
