"""Check changes and determine if we can skip some tests"""
from __future__ import print_function, unicode_literals

import os
import re
import subprocess
import sys

NOT_PYTHON = (
    r'themes(-default)?',
    r'yarn.lock',  # generated by yarn install
    r'.github/',
    r'readme.md',
)
FILE_REGEXP = re.compile(r'|'.join(NOT_PYTHON), re.IGNORECASE)

TRAVIS = os.environ.get('TRAVIS', False)


def graceful_exit(exitcode):
    if TRAVIS:
        print('travis_fold:end:medusa.check-changes')
    sys.exit(exitcode)


if TRAVIS:
    print('travis_fold:start:medusa.check-changes')

cmd = ['git', 'diff', '--name-only', 'HEAD^']
proc = subprocess.Popen(cmd, stdout=subprocess.PIPE)
(output, err) = proc.communicate()
changes = output.strip()
if err or not changes:
    print('Error while getting changed file list')
    graceful_exit(1)

changed_files = [' * ' + file for file in changes.split('\n') if file and not FILE_REGEXP.match(file)]
if not changed_files:
    print('Skipping Python tests...')
    graceful_exit(1)

print('Not skipping Python tests, found changed files:\n{0}'.format('\n'.join(changed_files)))
graceful_exit(0)
