approve_by_comment: true
approve_regex: (^Approved|^RTM)
reject_regex: (^Rejected|^Fix it)
reset_on_push: false
reviewers:
  -
    name: devs
    required: 1
    members:
      - duramato
      - fernandog
      - labrys
      - medariox
      - ratoaq2
      - p0psicles
      - OmgImAlexis
      - adaur
