# coding=utf-8
# Author: p0psicles
#
# This file is part of Medusa.
#
# Medusa is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Medusa is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Medusa. If not, see <http://www.gnu.org/licenses/>.

"""Custom exceptions used or raised by tvdbv2_api."""

__author__ = "p0psicles"
__version__ = "1.0"

__all__ = ["tvdbv2_error", "tvdbv2_userabort", "tvdbv2_shownotfound", "tvdbv2_showincomplete",
           "tvdbv2_seasonnotfound", "tvdbv2_episodenotfound", "tvdbv2_attributenotfound"]


class tvdbv2_exception(Exception):
    """Any exception generated by tvdbv2_api
    """
    pass


class tvdbv2_error(tvdbv2_exception):
    """An error with thetvdb.com (Cannot connect, for example)
    """
    pass


class tvdbv2_userabort(tvdbv2_exception):
    """User aborted the interactive selection (via
    the q command, ^c etc)
    """
    pass


class tvdbv2_shownotfound(tvdbv2_exception):
    """Show cannot be found on thetvdb.com (non-existant show)
    """
    pass


class tvdbv2_showincomplete(tvdbv2_exception):
    """Show found but incomplete on thetvdb.com (incomplete show)
    """
    pass


class tvdbv2_seasonnotfound(tvdbv2_exception):
    """Season cannot be found on thetvdb.com
    """
    pass


class tvdbv2_episodenotfound(tvdbv2_exception):
    """Episode cannot be found on thetvdb.com
    """
    pass


class tvdbv2_attributenotfound(tvdbv2_exception):
    """Raised if an episode does not have the requested
    attribute (such as a episode name)
    """
    pass
