# coding=utf-8
# Author: p0psicles
#
# This file is part of Medusa.
#
# Medusa is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Medusa is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Medusa. If not, see <http://www.gnu.org/licenses/>.

"""Custom exceptions used or raised by imdb_api."""

__author__ = "p0psicles"
__version__ = "1.0"

__all__ = ["imdb_error", "imdb_userabort", "imdb_shownotfound", "imdb_showincomplete",
           "imdb_seasonnotfound", "imdb_episodenotfound", "imdb_attributenotfound"]


class imdb_exception(Exception):
    """Any exception generated by imdb_api
    """
    pass


class imdb_error(imdb_exception):
    """An error with the indexer (Cannot connect, for example)
    """
    pass


class imdb_userabort(imdb_exception):
    """User aborted the interactive selection (via
    the q command, ^c etc)
    """
    pass


class imdb_shownotfound(imdb_exception):
    """Show cannot be found on the indexer (non-existant show)
    """
    pass


class imdb_showincomplete(imdb_exception):
    """Show found but incomplete on the indexer (incomplete show)
    """
    pass


class imdb_seasonnotfound(imdb_exception):
    """Season cannot be found on indexer.
    """
    pass


class imdb_episodenotfound(imdb_exception):
    """Episode cannot be found on the indexer
    """
    pass


class imdb_attributenotfound(imdb_exception):
    """Raised if an episode does not have the requested
    attribute (such as a episode name)
    """
    pass
