# coding=utf-8
# Author: p0psicles
#
# This file is part of Medusa.
#
# Medusa is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Medusa is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Medusa. If not, see <http://www.gnu.org/licenses/>.

"""Custom exceptions used or raised by tvmaze api."""
from __future__ import unicode_literals

__author__ = 'p0psicles'
__version__ = '1.0'

__all__ = ['TvmazeException', 'TvmazeError', 'TvmazeUserAbort', 'TvmazeShowNotFound', 'TvmazeShowIncomplete',
           'TvmazeSeasonNotFound', 'TvmazeEpisodeNotFound', 'TvmazeAttributeNotFound']


class TvmazeException(Exception):
    """Any exception generated by tvmaze_api."""


class TvmazeError(TvmazeException):
    """An error with thetvdb.com (Cannot connect, for example)."""


class TvmazeUserAbort(TvmazeException):
    """User aborted the interactive selection (via the q command, ^c etc)."""


class TvmazeShowNotFound(TvmazeException):
    """Show cannot be found on thetvdb.com (non-existant show)."""


class TvmazeShowIncomplete(TvmazeException):
    """Show found but incomplete on thetvdb.com (incomplete show)."""


class TvmazeSeasonNotFound(TvmazeException):
    """Season cannot be found on thetvdb.com."""


class TvmazeEpisodeNotFound(TvmazeException):
    """Episode cannot be found on thetvdb.com."""


class TvmazeAttributeNotFound(TvmazeException):
    """Raised if an episode does not have the requested attribute (such as a episode name)."""
