# coding=utf-8
# Author: p0psicles
#
# This file is part of SickRage.
#
# SickRage is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SickRage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with SickRage. If not, see <http://www.gnu.org/licenses/>.

"""Custom exceptions used or raised by anidb_api
"""

__author__ = "p0psicles"
__version__ = "1.0"

__all__ = ["anidb_error", "anidb_userabort", "anidb_shownotfound", "anidb_showincomplete",
           "anidb_seasonnotfound", "anidb_episodenotfound", "anidb_attributenotfound"]


class anidb_exception(Exception):
    """Any exception generated by anidb_api
    """
    pass


class anidb_error(anidb_exception):
    """An error with thetvdb.com (Cannot connect, for example)
    """
    pass


class anidb_userabort(anidb_exception):
    """User aborted the interactive selection (via
    the q command, ^c etc)
    """
    pass


class anidb_shownotfound(anidb_exception):
    """Show cannot be found on thetvdb.com (non-existant show)
    """
    pass


class anidb_showincomplete(anidb_exception):
    """Show found but incomplete on thetvdb.com (incomplete show)
    """
    pass


class anidb_seasonnotfound(anidb_exception):
    """Season cannot be found on thetvdb.com
    """
    pass


class anidb_episodenotfound(anidb_exception):
    """Episode cannot be found on thetvdb.com
    """
    pass


class anidb_attributenotfound(anidb_exception):
    """Raised if an episode does not have the requested
    attribute (such as a episode name)
    """
    pass
