dry-run: null
hookfiles: dredd/dredd_hook.py
language: python
sandbox: false
server: python dredd/dredd_hook.py
server-wait: 15
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 1000
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: dredd.yml
blueprint: dredd/api-description.yml
endpoint: 'http://127.0.0.1:8081'
