dry-run: null
hookfiles: dredd/dredd_hook.py
language: python
server: python dredd/dredd_hook.py
server-wait: 30
init: false
names: false
only: []
output: []
header: []
user: null
inline-errors: false
details: false
method: []
color: true
loglevel: warning
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 500
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
blueprint: dredd/api-description.yml
endpoint: 'http://localhost:8081'
